import type { Category, Coupon } from "./types";

export const categories: Category[] = [
  { id: "cafe", name: "스터디카페·카페", emoji: "☕", description: "스터디카페 이용권부터 카페 음료까지" },
  { id: "food", name: "외식·배달", emoji: "🍽️", description: "맛집·프랜차이즈 식사권" },
  { id: "beauty", name: "뷰티·헬스", emoji: "💆", description: "미용실·네일·헬스장" },
  { id: "culture", name: "문화·여가", emoji: "🎬", description: "영화·전시·체험" },
  { id: "shopping", name: "쇼핑", emoji: "🛍️", description: "브랜드 할인쿠폰" },
  { id: "gift", name: "기프트카드", emoji: "🎁", description: "어디서나 쓰는 금액권" },
];

export const coupons: Coupon[] = [
  {
    id: "letmeup-studycafe-4h",
    title: "렛미업 스터디카페 4시간 이용권",
    brand: "렛미업",
    category: "cafe",
    price: 4900,
    listPrice: 7000,
    thumb: "from-brand to-brand-dark",
    summary: "전국 렛미업 가맹 스터디카페에서 사용 가능한 4시간 시간권",
    description:
      "전국 렛미업 무인 스터디카페 어디서나 사용 가능한 4시간 시간권입니다. 키오스크에서 쿠폰번호 입력 한 번이면 바로 입실할 수 있어요. 집중이 필요한 날, 부담 없는 가격으로 만나보세요.",
    validity: "구매일로부터 90일",
    usage: ["전국 렛미업 가맹점 키오스크에서 쿠폰번호 입력", "1인 1매 사용", "잔여시간 이월 불가"],
    stock: null,
    seller: "렛미업",
    badges: ["베스트", "30% 할인"],
    featured: true,
  },
  {
    id: "letmeup-studycafe-1month",
    title: "렛미업 스터디카페 1개월 정기권",
    brand: "렛미업",
    category: "cafe",
    price: 99000,
    listPrice: 132000,
    thumb: "from-cyan-500 to-blue-600",
    summary: "한 달 무제한 이용. 시험기간 집중에 딱",
    description:
      "한 달 동안 매일 무제한으로 이용할 수 있는 정기권입니다. 시험기간, 자격증 준비, 취업 준비에 가장 인기 있는 상품이에요.",
    validity: "등록일로부터 30일",
    usage: ["전국 렛미업 가맹점 키오스크 또는 모바일앱에서 등록", "양도 불가", "일시정지 1회 가능"],
    stock: 200,
    seller: "렛미업",
    badges: ["인기", "25% 할인"],
    featured: true,
  },
  {
    id: "megacoffee-americano-2",
    title: "메가커피 아메리카노 2잔",
    brand: "메가MGC커피",
    category: "cafe",
    price: 2900,
    listPrice: 4000,
    thumb: "from-yellow-400 to-amber-500",
    summary: "가성비 끝판왕 아메리카노 2잔 교환권",
    description: "전국 메가커피 매장에서 아메리카노(ICE/HOT) 2잔으로 교환 가능한 모바일 교환권입니다.",
    validity: "구매일로부터 60일",
    usage: ["매장 직원에게 쿠폰번호 제시", "사이즈 업그레이드 시 차액 결제"],
    stock: 500,
    seller: "기프티몰",
    badges: ["27% 할인"],
    featured: true,
  },
  {
    id: "bhc-chicken-set",
    title: "BHC 뿌링클 + 콜라 1.25L",
    brand: "BHC",
    category: "food",
    price: 18900,
    listPrice: 23000,
    thumb: "from-red-500 to-rose-600",
    summary: "국민 치킨 뿌링클 세트 교환권",
    description: "BHC 대표 메뉴 뿌링클 한 마리와 콜라 1.25L 세트 교환권입니다. 배달앱 또는 매장에서 사용하세요.",
    validity: "구매일로부터 30일",
    usage: ["매장 방문 또는 전화주문 시 쿠폰번호 제시", "일부 매장 배달비 별도"],
    stock: 300,
    seller: "기프티몰",
    badges: ["인기"],
    featured: true,
  },
  {
    id: "baskin-pint",
    title: "배스킨라빈스 파인트",
    brand: "배스킨라빈스",
    category: "food",
    price: 7900,
    listPrice: 9900,
    thumb: "from-pink-400 to-fuchsia-500",
    summary: "골라먹는 즐거움, 파인트 교환권",
    description: "배스킨라빈스 파인트(2~3인분) 아이스크림 교환권입니다.",
    validity: "구매일로부터 60일",
    usage: ["매장에서 쿠폰번호 제시", "일부 프리미엄 맛 추가금 발생"],
    stock: null,
    seller: "기프티몰",
    badges: ["20% 할인"],
  },
  {
    id: "oliveyoung-30000",
    title: "올리브영 모바일 금액권 3만원",
    brand: "올리브영",
    category: "beauty",
    price: 27900,
    listPrice: 30000,
    thumb: "from-lime-500 to-green-600",
    summary: "전 매장·온라인몰에서 쓰는 3만원 금액권",
    description: "올리브영 전국 매장 및 온라인몰에서 현금처럼 사용 가능한 모바일 금액권입니다.",
    validity: "구매일로부터 5년",
    usage: ["매장: 바코드 제시 / 온라인몰: 쿠폰번호 등록", "잔액 분할 사용 가능"],
    stock: 150,
    seller: "기프티몰",
    badges: ["7% 할인"],
    featured: true,
  },
  {
    id: "cgv-movie-2",
    title: "CGV 영화 관람권 2매",
    brand: "CGV",
    category: "culture",
    price: 19800,
    listPrice: 28000,
    thumb: "from-slate-700 to-slate-900",
    summary: "주말·심야 상관없이 2D 영화 2매",
    description: "전국 CGV에서 사용 가능한 2D 영화 관람권 2매입니다. 요일·시간 제한 없이 사용하세요.",
    validity: "구매일로부터 90일",
    usage: ["CGV 홈페이지/앱에서 예매 시 쿠폰번호 입력", "특별관 차액 결제"],
    stock: 100,
    seller: "컬처박스",
    badges: ["29% 할인", "인기"],
  },
  {
    id: "fitness-1day-pass-10",
    title: "동네 헬스장 1일권 10회 묶음",
    brand: "스마트짐",
    category: "beauty",
    price: 49000,
    listPrice: 70000,
    thumb: "from-indigo-500 to-violet-600",
    summary: "부담 없이 시작하는 헬스 1일권 10회",
    description: "제휴 헬스장에서 자유롭게 사용할 수 있는 1일권 10회 묶음권입니다. 운동 입문자에게 추천해요.",
    validity: "구매일로부터 180일",
    usage: ["제휴 헬스장 데스크에서 쿠폰번호 제시", "지점별 운영시간 상이"],
    stock: 80,
    seller: "스마트짐",
    badges: ["30% 할인"],
  },
  {
    id: "starbucks-30000",
    title: "스타벅스 e기프트카드 3만원",
    brand: "스타벅스",
    category: "gift",
    price: 28500,
    listPrice: 30000,
    thumb: "from-emerald-600 to-green-800",
    summary: "선물하기 좋은 스타벅스 금액권",
    description: "스타벅스 전국 매장에서 사용 가능한 모바일 e기프트카드입니다. 선물용으로 인기 만점.",
    validity: "충전일로부터 2년",
    usage: ["사이렌오더 또는 매장에서 바코드 제시", "잔액 사용 가능"],
    stock: null,
    seller: "기프티몰",
    badges: ["5% 할인"],
  },
  {
    id: "coupang-eats-15000",
    title: "쿠팡이츠 배달 할인쿠폰 1.5만원",
    brand: "쿠팡이츠",
    category: "food",
    price: 11900,
    listPrice: 15000,
    thumb: "from-sky-500 to-blue-700",
    summary: "배달 주문 시 바로 차감되는 할인쿠폰",
    description: "쿠팡이츠 앱에서 등록 후 배달 주문 금액에서 차감되는 할인쿠폰입니다.",
    validity: "등록일로부터 30일",
    usage: ["쿠팡이츠 앱 > 쿠폰함에 코드 등록", "최소주문금액 1.5만원 이상"],
    stock: 200,
    seller: "딜팩토리",
    badges: ["20% 할인"],
  },
  {
    id: "yes24-20000",
    title: "예스24 도서 상품권 2만원",
    brand: "예스24",
    category: "culture",
    price: 18600,
    listPrice: 20000,
    thumb: "from-blue-600 to-indigo-700",
    summary: "도서·문구·음반에 쓰는 온라인 상품권",
    description: "예스24 온라인몰에서 도서, 문구, 음반 구매 시 사용 가능한 상품권입니다.",
    validity: "등록일로부터 5년",
    usage: ["예스24 마이페이지에서 핀번호 등록", "잔액 적립 후 사용"],
    stock: null,
    seller: "컬처박스",
    badges: ["7% 할인"],
  },
  {
    id: "musinsa-50000",
    title: "무신사 적립금 5만원권",
    brand: "무신사",
    category: "shopping",
    price: 45000,
    listPrice: 50000,
    thumb: "from-zinc-700 to-black",
    summary: "패션 쇼핑에 쓰는 무신사 적립금",
    description: "무신사 스토어에서 현금처럼 사용 가능한 적립금 충전권입니다.",
    validity: "등록일로부터 1년",
    usage: ["무신사 앱/웹 마이페이지에서 코드 등록", "결제 시 적립금 사용 선택"],
    stock: 120,
    seller: "딜팩토리",
    badges: ["10% 할인", "인기"],
  },
];

export function getCoupon(id: string): Coupon | undefined {
  return coupons.find((c) => c.id === id);
}

export function getCategory(id: string): Category | undefined {
  return categories.find((c) => c.id === id);
}

export function discountRate(c: Coupon): number {
  if (c.listPrice <= 0 || c.listPrice <= c.price) return 0;
  return Math.round((1 - c.price / c.listPrice) * 100);
}
